ALTER TABLE `CommissionRequest`
  MODIFY `status` ENUM(
    'PENDING',
    'REVIEWED',
    'INQUIRY',
    'PROPOSED',
    'CLIENT_ACCEPTED',
    'CLIENT_REJECTED',
    'ACCEPTED',
    'PAYMENT_PENDING',
    'IN_PROGRESS',
    'DELIVERED',
    'REVISION_REQUESTED',
    'COMPLETED',
    'REJECTED',
    'CANCELLED_BY_CLIENT',
    'CANCELLED_BY_ARTIST',
    'DISPUTED'
  ) NOT NULL DEFAULT 'PENDING';

ALTER TABLE `Review`
  ADD COLUMN `isPublic` BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE `ClientReview`
  ADD COLUMN `isPublic` BOOLEAN NOT NULL DEFAULT false;
