ALTER TABLE `JobPost`
  MODIFY `status` ENUM('OPEN', 'IN_REVIEW', 'ASSIGNED') NOT NULL DEFAULT 'OPEN';

ALTER TABLE `JobApplication`
  MODIFY `status` ENUM('PENDING', 'SHORTLISTED', 'ACCEPTED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
