-- AlterTable
ALTER TABLE `commissionrequest` ADD COLUMN `completedAt` DATETIME(3) NULL,
    ADD COLUMN `deliveredAt` DATETIME(3) NULL,
    ADD COLUMN `deliveryMessage` TEXT NULL,
    ADD COLUMN `deliveryUrl` VARCHAR(191) NULL,
    ADD COLUMN `revisionRequest` TEXT NULL,
    MODIFY `status` ENUM('PENDING', 'REVIEWED', 'PROPOSED', 'CLIENT_ACCEPTED', 'CLIENT_REJECTED', 'ACCEPTED', 'PAYMENT_PENDING', 'IN_PROGRESS', 'DELIVERED', 'REVISION_REQUESTED', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
