-- AlterTable
ALTER TABLE `commissionrequest` ADD COLUMN `rejectionReason` TEXT NULL,
    MODIFY `status` ENUM('PENDING', 'REVIEWED', 'PROPOSED', 'CLIENT_ACCEPTED', 'CLIENT_REJECTED', 'ACCEPTED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
